--------------------------------------------------------
--  File created - Friday-August-04-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SERVICES
--------------------------------------------------------

  CREATE TABLE "SAMPLE"."SERVICES" 
   (	"COID" NUMBER(4,0), 
	"VERSION" NUMBER(4,0), 
	"STATUS" VARCHAR2(20 BYTE), 
	"CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SAMPLE.SERVICES
SET DEFINE OFF;
Insert into SAMPLE.SERVICES (COID,VERSION,STATUS,CREATED) values (1,1,'created',to_date('19-APR-17','DD-MON-RR'));
Insert into SAMPLE.SERVICES (COID,VERSION,STATUS,CREATED) values (1,2,'pending',to_date('20-APR-17','DD-MON-RR'));
Insert into SAMPLE.SERVICES (COID,VERSION,STATUS,CREATED) values (1,3,'approved',to_date('21-APR-17','DD-MON-RR'));
Insert into SAMPLE.SERVICES (COID,VERSION,STATUS,CREATED) values (2,1,'created',to_date('21-APR-17','DD-MON-RR'));
Insert into SAMPLE.SERVICES (COID,VERSION,STATUS,CREATED) values (2,2,'pending',to_date('22-APR-17','DD-MON-RR'));
Insert into SAMPLE.SERVICES (COID,VERSION,STATUS,CREATED) values (2,3,'approved',to_date('23-APR-17','DD-MON-RR'));
Insert into SAMPLE.SERVICES (COID,VERSION,STATUS,CREATED) values (3,1,'created',to_date('23-APR-17','DD-MON-RR'));
Insert into SAMPLE.SERVICES (COID,VERSION,STATUS,CREATED) values (3,2,'pending',to_date('24-APR-17','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index SERVICES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAMPLE"."SERVICES_PK" ON "SAMPLE"."SERVICES" ("COID", "VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SERVICES
--------------------------------------------------------

  ALTER TABLE "SAMPLE"."SERVICES" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SAMPLE"."SERVICES" ADD CONSTRAINT "SERVICES_PK" PRIMARY KEY ("COID", "VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SAMPLE"."SERVICES" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "SAMPLE"."SERVICES" MODIFY ("COID" NOT NULL ENABLE);
